### ISSUE TITLE
Disable Tailwind preflight

### ISSUE THREAD

**Issue by leekaimun** [lara-zeus/sky#59]
In blog post and page, the rich editor allows text to be formatted with the basic HTML tags. However, these formatting are lost when the post or page is rendered on the browser. My guess is that Tailwind Preflight is normalising all these formatting. What is the best way to disable Tailwind Preflight?

**Comment by atmonshi** [comment]
I think the "fastest way" will be to create your tailwind build
and include the typography plugin
then add `prose` class to `post.blade.php`

I don't recommend removing Tailwind Preflight since it will cause other issues. 

I will look into including the typography plugin in the core and support this out of the box.

**Comment by atmonshi** [comment]
actually, the typography plugin is already in the core, so I will update the blade files to include the needed classes and release it today.

**Comment by atmonshi** [comment]
#60

**Comment by leekaimun** [comment]
Works great! Thanks!
